runtime: nodejs18
env: standard

# Static file handlers for Next.js export
handlers:
# Handle all static files first
- url: /_next/static/(.*)
  static_files: out/_next/static/\1
  upload: out/_next/static/(.*)
  expiration: "1y"

- url: /_next/(.*)
  static_files: out/_next/\1
  upload: out/_next/(.*)

# Handle other static files
- url: /(.*\.(js|css|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
  static_files: out/\1
  upload: out/(.*\.(js|css|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
  expiration: "1y"

# Handle API routes (if needed for server-side functionality)
- url: /api/.*
  script: auto

# Handle all other routes with index.html (for client-side routing)
- url: /.*
  static_files: out/index.html
  upload: out/index.html
  mime_type: text/html

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
