# Cloud Build configuration for Google Cloud Platform
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout for the entire build
timeout: '1200s'

# Substitutions (can be overridden when triggering the build)
substitutions:
  _PROJECT_ID: '${PROJECT_ID}'
  _REGION: 'us-central1'
